parameters:
    toxyy.postformtemplates.tables.pft_templates_table: '%core.table_prefix%pft_templates'
    toxyy.postformtemplates.tables.pft_template_forums_table: '%core.table_prefix%pft_template_forums'
    toxyy.postformtemplates.tables.pft_template_entries_table: '%core.table_prefix%pft_template_entries'
    toxyy.postformtemplates.tables.pft_template_images_table: '%core.table_prefix%pft_template_images'
    toxyy.postformtemplates.paths.pft_image_path: '%core.root_path%ext/toxyy/postformtemplates/images'
    toxyy.postformtemplates.constants.template_form: '1'
    toxyy.postformtemplates.constants.template_cat: '0'
    toxyy.postformtemplates.constants.entry_text: '0'
    toxyy.postformtemplates.constants.entry_radio: '1'
    toxyy.postformtemplates.constants.entry_checkbox: '2'
    toxyy.postformtemplates.constants.entry_dropdown: '3'
    toxyy.postformtemplates.constants.entry_textnote: '4'
services:
    toxyy.postformtemplates.main:
        class: toxyy\postformtemplates\event\main
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@language'
            - '@template'
            - '@config'
            - '@user'
            - '@auth'
            - '@content.visibility'
            - '@toxyy.postformtemplates.auth_admin_helper'
            - '%toxyy.postformtemplates.paths.pft_image_path%'
            - '%toxyy.postformtemplates.tables.pft_templates_table%'
            - '%toxyy.postformtemplates.tables.pft_template_forums_table%'
            - '%toxyy.postformtemplates.tables.pft_template_entries_table%'
            - '%toxyy.postformtemplates.tables.pft_template_images_table%'
            - '%toxyy.postformtemplates.constants.entry_text%'
            - '%toxyy.postformtemplates.constants.entry_radio%'
            - '%toxyy.postformtemplates.constants.entry_checkbox%'
            - '%toxyy.postformtemplates.constants.entry_dropdown%'
            - '%toxyy.postformtemplates.constants.entry_textnote%'
        tags:
            - { name: event.listener }
    toxyy.postformtemplates.auth_admin_helper:
        class: toxyy\postformtemplates\controller\auth_admin_helper
        arguments:
            - '@cache.driver'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@language'
            - '@template'
            - '@group_helper'
            - '@acl.permissions'
            - '@toxyy.postformtemplates.manage_templates_helper'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '%toxyy.postformtemplates.tables.pft_templates_table%'
    toxyy.postformtemplates.manage_templates_helper:
        class: toxyy\postformtemplates\controller\manage_templates_helper
        arguments:
            - '@cache.driver'
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '@auth'
            - '@language'
            - '@template'
            - '@log'
            - '@toxyy.postformtemplates.template_permissions_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%toxyy.postformtemplates.tables.pft_templates_table%'
            - '%toxyy.postformtemplates.tables.pft_template_forums_table%'
            - '%toxyy.postformtemplates.tables.pft_template_entries_table%'
            - '%toxyy.postformtemplates.tables.pft_template_images_table%'
            - '%toxyy.postformtemplates.constants.template_form%'
            - '%toxyy.postformtemplates.constants.template_cat%'
    toxyy.postformtemplates.template_permissions_helper:
        class: toxyy\postformtemplates\controller\template_permissions_helper
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@language'
            - '@log'
            - '@group_helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%toxyy.postformtemplates.tables.pft_templates_table%'
            - '%toxyy.postformtemplates.constants.template_form%'
            - '%toxyy.postformtemplates.constants.template_cat%'
    toxyy.postformtemplates.modules.template_entries:
        class: toxyy\postformtemplates\modules\template_entries
        arguments:
            - '@cache.driver'
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '@language'
            - '@template'
            - '@log'
            - '@text_formatter.acp_utils'
            - '@text_formatter.cache'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '%toxyy.postformtemplates.tables.pft_template_entries_table%'
            - '%toxyy.postformtemplates.constants.entry_text%'
            - '%toxyy.postformtemplates.constants.entry_radio%'
            - '%toxyy.postformtemplates.constants.entry_checkbox%'
            - '%toxyy.postformtemplates.constants.entry_dropdown%'
            - '%toxyy.postformtemplates.constants.entry_textnote%'
